### ISSUE TITLE
PhotoEditorSDK/PhotoEditorSDK-swift.h file not found

### ISSUE THREAD

**Issue by roycclu** [interw3bs/photo-editor-sdk-react-native#3]
Successfully installed. Linked. Then ran into this problem at build. 
Any idea why?

Problem pointing at following lines:
#import <PhotoEditorSDK/PhotoEditorSDK-swift.h>

Problem log:
```
"PhotoEditorSDK/PhotoEditorSDK-swift.h" not found
```
photo-editor-sdk-react-native v1.1.1
React v0.11.0
PhotoEditorSDK 8.2.4
AVHexcOLOR 3.0.0
Pod 1.4.0
React-Naitve 0.47.0
XCode 9.2

**Comment by roycclu** [comment]
@tastenjesus 
Hey man. Really appreciate this library. 
Submitted a PR to help others avoid a missing step. 

Still the error above shows. Any help welcome. 
Would really love to use this library.

**Comment by caesar3x** [comment]
I got the same issue. Could anyone help?

**Comment by michelalbers** [comment]
Thanks @roycclu for you PRs! Merged them both and will work on an update of the library soon to incorporate the most recent versions of PESDK. Sorry for the long delays though :/
