### ISSUE TITLE
Notes on Installation and a Question

### ISSUE THREAD

**Issue by vedmakk** [interw3bs/photo-editor-sdk-react-native#6]
Hi,

Thanks for your work! I installed the PhotoEditorSDK together with this module today and had to work around some caveats which might be good to add to the step-by-step guide in the readme:

Additionally to the steps in the readme, I had to:
- Add "#import <PhotoEditorSDK/PhotoEditorSDK.h>" to AppDelegate.m
- Make sure to have the right license file (with the correct bundle identifiert --> App will Crash on startup) --> This might be clear but worth noting ;)
- Set the Always Embed Swift Standard Libraries build setting in your project’s Build Settings tab to Yes.

After that I was able to call "openEditor" and open the PESDK within my App – However: The Photoeditor displays a "Loading image"-Screen that never disappears and the image won't be displayed.

I'm passing a "file:///..."-Url to PESDK that was selected from the camera roll. I noticed this in your docs:
«Note for iOS users: Since Apple is a bit restrictive on file system access you may have to fiddle with RNFetchBlob (https://github.com/wkh237/react-native-fetch-blob) to directly open the editor with an image filepath.»

Do I need to first fetch the file into local storage (using react-native-fetch-blob or react-native-fs) so that the image is accessible to PESDK? Or is this not related? Any experiences or similar issues?

Thank you!

**Comment by michelalbers** [comment]
Hi @protyze! Sorry for the long delay in answering this. iOS generates asset-urls which are not useable directly. In my app I user RNFetchBlob to convert the asset-url to a base64 image and open the editor with that. On android file:// is fine:

```TypeScript
const path = <result of image picker here>;

if (Platform.OS === 'ios') {
        const base64Image = await RNFetchBlob.fs.readFile(path, 'base64')
        const base64DataURL = `data:image/jpeg;base64,${base64data}`;

        // Use base64DataURL with PESDK (pseudocode)
        openEditor(base64DataURL);

} else {
       // Use regular path
        openEditor(path.replace('file://',''));
       
}
```

I think an update of this library is long overdue. I hope I can manage to do that soon. Any help is greatly appreciated via PR.

**Comment by vedmakk** [comment]
Hi @michelalbers 

I managed to solve it without the need for a base64 image with just little changes:

1. Use a PESDKImage rather than a UIImage to open the Editor:

```
(...)
-(void)_openEditor: (PESDKPhoto *)image config: (PESDKConfiguration *)config features: (NSArray*)features options:(NSDictionary *) options custom:(NSDictionary*) custom resolve: (RCTPromiseResolveBlock)resolve reject: (RCTPromiseRejectBlock)reject {
(...)
```

2. Initialize the PESDKPhotoEditViewControllor with a PhotoAsset (not Photo)

```
(...)
self.editController = [[PESDKPhotoEditViewController alloc] initWithPhotoAsset:image configuration:config menuItems:menuItems photoEditModel:photoEditModel];
(...)
```

3. Change the exported openEditor function to initialize a PESDKPhoto from the path.

```
RCT_EXPORT_METHOD(openEditor: (NSString*)path options: (NSArray *)features options: (NSDictionary*) options custom:(NSDictionary*) custom resolve: (RCTPromiseResolveBlock)resolve reject: (RCTPromiseRejectBlock)reject) {
    PESDKPhoto* image = [[PESDKPhoto alloc] initWithUrl:[NSURL URLWithString:path]];
    PESDKConfiguration* config = [self _buildConfig:options custom:custom];
	dispatch_sync(dispatch_get_main_queue(), ^{  
    	[self _openEditor:image config:config features:features options:options custom:custom resolve:resolve reject:reject];
	});
}
```

PESDKPhoto can handle asset-urls and also preserves image meta-data (like EXIF) which was needed in my use case.

I did these changes in a fork and can file a PR if interested. I used this version as a base: https://github.com/onstuimig/photo-editor-sdk-react-native , because it had some other improvements based on your last version.

I'm going to use PESDK with react-native in my current App, so I'm interested in helping to improve this module where I can.

**Comment by michelalbers** [comment]
Thank your for your work! I'm currently heavily busy and do not have time to maintain this project. If you like I could add you as maintainer to this project?

**Comment by franck-nadeau** [comment]
I needed that fix, so I did it. I also sent you a PR for it if you want it.
