### ISSUE TITLE
is there any reason why this wouldn't work along with your react native camera? 

### ISSUE THREAD

**Issue by ajkhatibi** [interw3bs/photo-editor-sdk-react-native#8]
whenever I install this and go through your guide I get an error about your react native camera. I'm also using your react native camera? any idea?

**Comment by michelalbers** [comment]
This project is unfortunetaly not very maintained since I don't have any ressources left for it. I don't know about the current situation with react-native-camera and its dependencies - sorry :(

**Comment by ajkhatibi** [comment]
i was able to figure it out but thank you!
